---
title: "Homework 4 Reporting Engine, Jinhan Cheng"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rmarkdown)
library(knitr)
library(Hmisc)
library(DT)
library(data.table)
assignInNamespace("cedta.override", c(data.table:::cedta.override,"rmarkdown"), "data.table")


opts_chunk$set(echo = FALSE, comment="", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=55), tidy = TRUE)

```


```{r read_data, include=FALSE}
dat <- fread(input = "Homework 4 Data -- 2017.csv", verbose = FALSE)
```

```{r process_data, include=FALSE}
save(list = c("dat"), file = "Homework 4 Data -- 2017.RData")
load(file = "Homework 4 Data -- 2017.RData")
```

```{r define_variables}
dat[, age.group := cut2(x = age, cuts = c(18, 35, 50, 65, 120))]
dat[, income.group := cut2(x = income, cuts = 1000* c(0, 50, 75, 100, 150, 250))]
dat[, Satisfaction := Satisfaction/10]

unique.age.groups <- dat[, unique(age.group)]
unique.age.groups <- sort(unique.age.groups, decreasing = FALSE)
unique.genders <- dat[, unique(gender)]
unique.income.groups <- dat[, unique(income.group)]
unique.income.groups <- sort(unique.income.groups, decreasing = FALSE)
unique.regions <- dat[, unique(region)]
unique.personas <- dat[, unique(persona)]
unique.products <- dat[, unique(Product)]
num.products <- length(unique.products)

respondent.variables <- c("age.group", "gender", "income.group", "region", "persona")
states.of.engagement <- c("Awareness", "Consideration", "Consumption", "Satisfaction", "Advocacy")
bp.traits <- names(dat)[grep(pattern = "BP_", x = names(dat))]
em.variables <- c(respondent.variables, bp.traits, "Aggregated.Engagement")
```

```{r functions}
percentage.table <- function(x, digits = 1){
  tab <- table(x)
  percentage.tab <- 100*tab/(sum(tab))
  rounded.tab <- round(x = percentage.tab, digits = digits)
  return(rounded.tab)
}

round.numerics <- function(x, digits){
  if(is.numeric(x)){
    x <- round(x = x, digits = digits)
  }
  return(x)
}

# Mean, remove NAs
mean.na.rm <- function(x) {
    return(mean(x, na.rm=TRUE))
}

# Clean up Names of Brand Perceptions
BP.name.cleanup <- function(x, removal.characters = c("BP", "0", "1")) {
  for (i in 1:length(x)) {
    x[i] <- gsub(pattern = "_", replacement = "", x = x[i], fixed = TRUE)
    for (j in 1:length(removal.characters)) {
      x[i] <- gsub(pattern = removal.characters[j], replacement = "", x = x[i], fixed = TRUE)
    } 
  }
  return(x) 
}
new.bp.traits <- BP.name.cleanup(x = bp.traits)
negative.traits <- c("Boring","Bulky","Fragile","Expensive")

# Dynamic Formulas
reduce.formula <- function(dat, the.initial.formula) {
    dat <- as.data.table(dat)
    
    the.sides <- strsplit(x = the.initial.formula, split = "~")[[1]]      
    the.pieces.untrimmed <- strsplit(x = the.sides[2], split = "+", fixed = TRUE)[[1]]
    the.pieces <- trimws(x = the.pieces.untrimmed, which = "both") 
    num.variables <- length(the.pieces)
    include.pieces <- logical(num.variables)
    
    for (i in 1:num.variables) {
        unique.values <- dat[, unique(get(the.pieces[i]))]
        if (length(unique.values) < 2) {
            include.pieces[i] <- FALSE 
        } else {
            include.pieces[i] <- TRUE 
        }
    }
    rhs <- paste(the.pieces[include.pieces == TRUE], collapse = " + ") 
    the.formula <- sprintf("%s ~ %s", trimws(x = the.sides[1]), rhs) 
    return(the.formula)
}

# Logistic Regression Summary
logistic.regression.summary <- function(glm.mod, digits = 3) {
  glm.coefs <- as.data.table(summary(glm.mod)$coefficients, keep.rownames = TRUE) 
  alpha = 0.05
  z <- qnorm(p = 1 - alpha/2, mean = 0, sd = 1)
  glm.coefs[, `:=`(Odds.Ratio, exp(Estimate))]
  glm.coefs[, `:=`(OR.Lower.95, exp(Estimate - z * `Std. Error`))] 
  glm.coefs[, `:=`(OR.Upper.95, exp(Estimate + z * `Std. Error`))] 
  setnames(x = glm.coefs, old = c("rn", "Pr(>|z|)"), new = c("Variable", 
    "p.value"))
  setcolorder(x = glm.coefs, neworder = c("Variable", "Estimate", 
    "Odds.Ratio", "OR.Lower.95", "OR.Upper.95", "p.value", "Std. Error", "z value"))
  return(glm.coefs[])
}

# Linear Regression Summary
linear.regression.summary <- function(lm.mod, digits = 3) { 
  lm.coefs <- as.data.table(summary(lm.mod)$coefficients, keep.rownames = TRUE) 
  alpha = 0.05
  z <- qnorm(p = 1 - alpha/2, mean = 0, sd = 1)
  lm.coefs[, `:=`(Coef.Lower.95, Estimate - z * `Std. Error`)] 
  lm.coefs[, `:=`(Coef.Upper.95, Estimate + z * `Std. Error`)] 
  setnames(x = lm.coefs, old = c("rn", "Pr(>|t|)"), new = c("Variable", 
    "p.value"))
  setcolorder(x = lm.coefs, neworder = c("Variable", "Estimate", "Coef.Lower.95", 
    "Coef.Upper.95", "p.value", "Std. Error", "t value"))
  return(lm.coefs)
}

# Model Fitting Function
fit.model <- function(dat, the.initial.formula, model.type, digits = 3) {
    the.formula <- reduce.formula(dat = dat, the.initial.formula = the.initial.formula)
    if (model.type == "logistic") {
        mod <- glm(formula = the.formula, family = "binomial", data = dat)
        mod.summary <- logistic.regression.summary(glm.mod = mod, digits = digits)
    }
    if (model.type == "linear") {
        mod <- lm(formula = the.formula, data = dat) 
        mod.summary <- linear.regression.summary(lm.mod = mod, digits = digits)
    }
    mod.summary.rounded <- mod.summary[, lapply(X = .SD, FUN = "round.numerics", digits = digits)] 
    return(mod.summary.rounded)
}

# Awareness Model
awareness.model <- function(dat, variables) {
    the.initial.formula <- sprintf("Awareness ~  %s ",
        paste(variables, collapse = " + "))
    res <- fit.model(dat = dat, the.initial.formula = the.initial.formula,
        model.type = "logistic") 
    return(res)
}

# Consideration Model
consideration.model <- function(dat, variables) {
    the.initial.formula <- sprintf("Consideration ~  %s ",
        paste(variables, collapse = " + "))
    res <- fit.model(dat = dat, the.initial.formula = the.initial.formula,
        model.type = "logistic") 
    return(res)
}

# Consumption Model
consumption.model <- function(dat, variables) {
    the.initial.formula <- sprintf("Consumption ~  %s ",
        paste(variables, collapse = " + "))
    res <- fit.model(dat = dat, the.initial.formula = the.initial.formula,
        model.type = "logistic") 
    return(res)
}

# Advocacy Model
advocacy.model <- function(dat, variables) {
    the.initial.formula <- sprintf("Advocacy ~  %s ",
        paste(variables, collapse = " + "))
    res <- fit.model(dat = dat, the.initial.formula = the.initial.formula,
        model.type = "logistic") 
    return(res)
}

# Satisfaction Model
satisfaction.model <- function(dat, variables) {
    the.initial.formula <- sprintf("Satisfaction ~  %s ",
        paste(variables, collapse = " + "))
    res <- fit.model(dat = dat, the.initial.formula = the.initial.formula,
        model.type = "linear") 
    return(res)
}

```


Introduction
=====================================  

We are analyzing data from the Marketing Department covering a variety of mobile phone products.  

The survey was given to `r dat[, length(unique(id))]` respondents and covered `r num.products` separate products.

Click on the tabs to see different reports.


Question 1
===================================


Row {data-height=500}
-------------------------------------

```{r respondents}
inputPanel(
  selectInput(inputId = "respondent_variable", label = "Select Variable:", choices = respondent.variables, selected = respondent.variables[1]),
  checkboxInput(inputId = "respondent_show_percentages", label = "Show Percentages", value = TRUE)
)


renderPlot({
  tab <- percentage.table(x = dat[Product == Product[1], get(input$respondent_variable)])
  barplot(height = tab, space = 0.01, las = 1, main = input$respondent_variable, ylab = "Percentage", xlab = input$respondent_variable, ylim = c(0, 1.2*max(tab, na.rm = TRUE)))
  if(input$respondent_show_percentages == TRUE){
    space_val = 0
    text(x = -0.4 + 1:length(tab)*(1 + space_val), y = tab, labels = sprintf("%.1f%%", tab), pos = 3)
  }
})
```

Question 2
=====================================  


Row {data-height=800}
-------------------------------------

```{r products}
inputPanel(
  selectInput(inputId = "product_info_engagement_state", label = "Select State of Engagement:", choices = states.of.engagement, selected = states.of.engagement[1]),
  checkboxInput(inputId = "product_info_decreasing2", label = "Sorted", value = TRUE),
  checkboxInput(inputId = "SE_show_percentages", label = "Show Percentages", value = TRUE),
  selectInput(inputId = "SE_age_group", label = "Age", choices = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "SE_gender", label = "Gender", choices = unique.genders, multiple = TRUE),
  selectInput(inputId = "SE_income_group", label = "Income", choices = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "SE_region", label = "Region", choices = unique.regions, multiple = TRUE),
  selectInput(inputId = "SE_persona", label = "Persona", choices = unique.personas, multiple = TRUE),
  sliderInput(inputId = "product_info_min_threshold2", label = "Show Products Above", min = 1, max = 20, value = 5, step = 1),
  sliderInput(inputId = "product_info_names_magnification2", label = "Magnify Product Names", min = 0.4, max = 1.4, value = 1, step = 0.1)
)


renderPlot({
  subdat2 <- dat[age.group %in% input$SE_age_group & gender %in% input$SE_gender & income.group %in% input$SE_income_group & region %in% input$SE_region & persona %in% input$SE_persona]
  rates <- subdat2[,.(Mean = 100*mean(get(input$product_info_engagement_state), na.rm = TRUE)), by = Product]
  
  if(input$product_info_decreasing2 == TRUE){
    setorderv(x = rates, cols = "Mean", order = -1, na.last = TRUE)
  }
  barplot(height = rates[1:input$product_info_min_threshold2, Mean], names.arg = rates[1:input$product_info_min_threshold2, Product], space = 0.01, las = 1, main = input$product_info_engagement_state, ylab = sprintf("Rate of %s", input$product_info_engagement_state), cex.names = input$product_info_names_magnification2, ylim = c(-100, 120), xaxt = "n", axes =F)
  axis(side = 2, at = 20*(0:5), las = 2)
  
  text(x = -0.5 + 1.02*1:rates[1:input$product_info_min_threshold2, .N], y = -15, labels = rates[1:input$product_info_min_threshold2, Product], srt = 45, cex = input$product_info_names_magnification2, pos = 2)
  
  if(input$SE_show_percentages == TRUE){
    space_val = 0
    text(x = -0.4 + 1:rates[1:input$product_info_min_threshold2, .N]*(1+space_val), y = rates[1:input$product_info_min_threshold2, Mean], labels = sprintf("%.1f%%", rates[1:input$product_info_min_threshold2, Mean]), pos = 3)
  }
})
```

Question 3
=====================================  

Row {data-height=500}
-------------------------------------

```{r brand_perceptions}
inputPanel(
  selectInput(inputId = "BP_age_group", label = "Age", choices = unique.age.groups, multiple = TRUE),
  selectInput(inputId = "BP_gender", label = "Gender", choices = unique.genders, multiple = TRUE),
  selectInput(inputId = "BP_income_group", label = "Income", choices = unique.income.groups, multiple = TRUE),
  selectInput(inputId = "BP_region", label = "Region", choices = unique.regions, multiple = TRUE),
  selectInput(inputId = "BP_persona", label = "Persona", choices = unique.personas, multiple = TRUE),
  checkboxInput(inputId = "product_info_decreasing3", label = "Sorted", value = TRUE),
  checkboxInput(inputId = "BP_show_scores", label = "Show Scores", value = TRUE),
  sliderInput(inputId = "product_info_min_threshold3", label = "Show Products Above", min = 1, max = 20, value = 5, step = 1),
  sliderInput(inputId = "product_info_names_magnification3", label = "Magnify Product Names", min = 0.4, max = 1.4, value = 1, step = 0.1)
)


renderPlot({
  subdat3 <- dat[age.group %in% input$BP_age_group & gender %in% input$BP_gender & income.group %in% input$BP_income_group & region %in% input$BP_region & persona %in% input$BP_persona]
#step1:
  bp_mean <- subdat3[, lapply(X = .SD, FUN = "mean.na.rm"), .SDcols =bp.traits, by=Product]
#step2:
  for (i in 1:length(new.bp.traits))
    {if( new.bp.traits[i] %in% negative.traits )
    {bp_mean[,i+1] <- 10-bp_mean[,i+1,with=FALSE]}
  }
#step3:
  bp_mean[,`:=`(Score, round(rowMeans(bp_mean[,2:ncol(bp_mean)],na.rm = TRUE), digits=1))]
  scores <- bp_mean[,c("Product","Score")]
#step4:
  if(input$product_info_decreasing3 == TRUE){
    setorderv(x = scores, cols = "Score", order = -1, na.last = TRUE)
  }
#step5:
  barplot(height = scores[1:input$product_info_min_threshold3, Score], names.arg = scores[1:input$product_info_min_threshold3, Product], space = 0.01, las = 1, main = "Overall Average Perception", ylab = "Score", cex.names = input$product_info_names_magnification3, ylim = c(-10, 12), xaxt = "n", axes =F)
  axis(side = 2, at = 2*(0:5), las = 2)

  text(x = -0.5 + 1.02*1:scores[1:input$product_info_min_threshold3, .N], y = -1.5, labels = scores[1:input$product_info_min_threshold3, Product], srt = 45, cex = input$product_info_names_magnification3, pos = 2)

  if(input$BP_show_scores == TRUE){
    space_val = 0
    text(x = -0.4 + 1:scores[1:input$product_info_min_threshold3, .N]*(1+space_val), y = scores[1:input$product_info_min_threshold3, Score], labels = scores[1:input$product_info_min_threshold3, Score], pos = 3)
  }
})

```

Question 4
=====================================  

Row {data-height=500}
-------------------------------------

```{r engagement_plots}
inputPanel(
  selectInput(inputId = "product_info_engagement_state4_1", label = "Select the First State of Engagement:", choices = states.of.engagement),
  selectInput(inputId = "product_info_engagement_state4_2", label = "Select the Second State of Engagement:", choices = states.of.engagement),
  checkboxInput(inputId = "product_info_decreasing4", label = "Sorted", value = TRUE),
  checkboxInput(inputId = "SE_show_percentages4", label = "Show Percentages", value = TRUE),
  sliderInput(inputId = "product_info_min_threshold4", label = "Show Products Above", min = 1, max = 20, value = 5, step = 1),
  sliderInput(inputId = "product_info_names_magnification4", label = "Magnify Product Names", min = 0.4, max = 1.4, value = 1, step = 0.1),
  sliderInput(inputId = "digits4", label = "Select Digits", min = 0, max = 10, value = 1, step = 1)
)

mean.diff <- function(x, y){
  return(mean(x, na.rm=TRUE) - mean(y, na.rm=TRUE))
}

renderPlot({
  rates4 <- dat[,.(Mean.diff = round.numerics(100*mean.diff(get(input$product_info_engagement_state4_1), get(input$product_info_engagement_state4_2)), input$digits4)), by = Product]
  
  if(input$product_info_decreasing4 == TRUE){
    setorderv(x = rates4, cols = "Mean.diff", order = -1, na.last = TRUE)
  }
  barplot(height = rates4[1:input$product_info_min_threshold4, Mean.diff], names.arg = rates4[1:input$product_info_min_threshold4, Product], space = 0.01, las = 1, main = sprintf("%s - %s", input$product_info_engagement_state4_1, input$product_info_engagement_state4_2), ylab = "Rate of Difference", cex.names = input$product_info_names_magnification4, ylim = c(-200, 120), xaxt = "n", axes =F)
  axis(side = 2, at = 20*(-5:5), las = 2)
  
  text(x = -0.5 + 1.02*1:rates4[1:input$product_info_min_threshold4, .N], y = -100, labels = rates4[1:input$product_info_min_threshold4, Product], srt = 45, cex = input$product_info_names_magnification4, pos = 2)
  
  if(input$SE_show_percentages4 == TRUE){
    space_val = 0
    text(x = -0.4 + 1:rates4[1:input$product_info_min_threshold4, .N]*(1+space_val), y = rates4[1:input$product_info_min_threshold4, Mean.diff], labels = paste( rates4[1:input$product_info_min_threshold4, Mean.diff],"%",sep=""), pos = 3)
  }  
})

```

Question 5
=====================================  

Row {data-height=300}
-------------------------------------


```{r engagement_models}
inputPanel(
  selectInput(inputId = "em_product", label = "Select Brand:", choices = unique.products, selected ="Buzzdial"),
  selectInput(inputId = "em_state", label = "Select State of Engagement:", choices = states.of.engagement, selected = "Awareness"),
  selectInput(inputId = "em_variables", label = "Select Variables:", choices = em.variables, selected = em.variables, multiple = TRUE)
)


renderDataTable({
   dat$Aggregated.Engagement <- NULL
   dat[!(Product %in% input$em_product), ':='(Aggregated.Engagement, mean(get(input$em_state),na.rm=TRUE)),by=id]
   dat[,':='(Aggregated.Engagement,mean(Aggregated.Engagement,na.rm=TRUE)),by=id]
   subdat5 <- dat[Product %in% input$em_product]
   subdat5[, Satisfaction := Satisfaction*10]
   if(input$em_state == "Satisfaction"){
     subdat5[, Aggregated.Engagement := Aggregated.Engagement*10] 
   }
   
   if(input$em_state == "Awareness"){
     res <- awareness.model(dat = subdat5, variables = input$em_variables)
   }
   if(input$em_state == "Consideration"){
     res <- consideration.model(dat = subdat5, variables = input$em_variables)
   }
   if(input$em_state == "Consumption"){
     res <- consumption.model(dat = subdat5, variables = input$em_variables)
   }
   if(input$em_state == "Advocacy"){
     res <- advocacy.model(dat = subdat5, variables = input$em_variables)
   }
   if(input$em_state == "Satisfaction"){
     res <- satisfaction.model(dat = subdat5, variables = input$em_variables)
   }  
   datatable(data = res)
})

```

Row {data-height=700}
-------------------------------------
